### ISSUE TITLE
Resolve "Your account needs to be vetted in order to publish"

### ISSUE THREAD

**Issue by edburns** [WASdev/azure.websphere-traditional.image#18]
Tried to publish the hidden VM offer. Encountered this message.

![image](https://user-images.githubusercontent.com/75821/116948290-00c06480-ac4d-11eb-8373-6e54a3bed0ac.png)

Does @gcharters or @git4rk see this when they try to publish?

**Comment by edburns** [comment]
Confirmed that @gcharters  also sees this.  Did not try @git4rk . We are dead in the water until this is resolved.

**Comment by edburns** [comment]
* I will follow [these steps](https://docs.microsoft.com/en-us/azure/marketplace/azure-vm-create-plans) to ensure the plan is hidden.

**Comment by edburns** [comment]
I am trying to get access to ticket 2105120040006459.  The information I am filling in now is the same as for that ticket.

* In Partner Center, select Directory **IBM-Alliance-Microsoft Partner Network-Global-Tenant**.
* In the left navigation panel, select **Commercial Marketplace** : **Overview**.
* In the **Offers** table, select **2021-04-27-twas-cluster-base-image**.
* In the middle navigation panel, select **Plan overview**.
* In the **Plan overview** table, select **2021-04-27-twas-cluster-base-image**.
* In the middle navigation panel, select **Plan listing**.
* At the bottom of the page select **Review and publish**.
* On the page that loads, note a red text above a grayed out **Publish** button which says, "Your account needs to be vetted in order to publish an offer to the marketplace. View your account verification status and take any action if required."

**Comment by edburns** [comment]
Hello @git4rk @gcharters , I now observe this problem seems to be resolved. Please close this issue.

**Comment by edburns** [comment]
I spoke too soon.  This is not resolved. I was looking at the wrong partner center account.

**Comment by gcharters** [comment]
@edburns I've chased this again. :(   Are you able to see any updates in the ticket?

**Comment by edburns** [comment]
From support:

```
Hello Edward,
 
Hope this email finds you well!

We are unable to verify  Microsoft Partner Network account for seller id: ***** because the email was not verified within 30 days.  
The email address  may be changed from  Partner Center Dashboard or resend option can be selected.  

The verification email was sent to: g***b@***m.com
 
Thank you and best regards, 
 
Microsoft Partner Network support team 

```

**Comment by edburns** [comment]
From IBM:

```
Bruce A:
g***b@***m.com did reply with the confirmation email. The system is not equipped to handle the way our MPN is set up to ride this process to completion. I have escalated the AI Ops publisher and others back to support. I expect to get an update today on a manual process that can complete the request. I will give you the updates asap.
```

**Comment by edburns** [comment]
I have been given the following names to push this from the Microsoft side.
* Jennifer Burgdorf
* Monica Cao
* Cedric Stroehnisch

**Comment by edburns** [comment]
I am happy to report that the vetting issue seems to have been resolved, as evidenced by my ability to select **Review and 
 publish** as shown here:

![image](https://user-images.githubusercontent.com/75821/119026449-2ea6e800-b973-11eb-856f-a27a316fbcb3.png)

**Comment by edburns** [comment]
https://ibm-cloud.slack.com/archives/G010BB252NA/p1621533598047900
