### ISSUE TITLE
Set up CI/CD to build, test and upload the image to ObjectStore

### ISSUE THREAD

**Issue by git4rk** [WASdev/azure.websphere-traditional.image#2]
Also document any manual steps

**Comment by edburns** [comment]
@git4rk  can you please assign this to @zhengchang907 .

**Comment by zhengchang907** [comment]
PR: https://github.com/WASdev/azure.websphere-traditional.image/pull/16

**Comment by edburns** [comment]
Hello @git4rk, the pipeline ran successfully, please see [this run](https://github.com/WASdev/azure.websphere-traditional.image/actions/runs/840797924). This issue can be closed.

**Comment by zhengchang907** [comment]
@git4rk Hi Ranjan, can you please review and close this issue?
