### ISSUE TITLE
Obtain values for secrets needed to run pipeline

### ISSUE THREAD

**Issue by edburns** [WASdev/azure.websphere-traditional.image#21]
```
USER_NAME
AZURE_CREDENTIALS
UNENTITLED_IBM_USER_ID
UNENTITLED_IBM_USER_PWD
ENTITLED_IBM_USER_ID
ENTITLED_IBM_USER_PWD
MSTEAMS_WEBHOOK
```

**Comment by edburns** [comment]
* userName: ${{ secrets.USER_NAME }}
   * This should be the `WASdev`. This string is prepended like so for downloading `https://raw.githubusercontent.com/${git.repo}`

**Comment by edburns** [comment]
### Service Principal

* `azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}`

   ```bash
   export SUBSCRIPTION_ID=<subscription id for Azure WebSphere Collaboration Sponsorship
     It starts with 1970. You can get it from the portal>
   export SP_NAME=20210512_IBM_SP
   az ad sp create-for-rbac --name ${SP_NAME} --sdk-auth --role contributor --scopes /subscriptions/${SUBSCRIPTION_ID}
   ```

* From [GitHub actions docs](https://github.com/marketplace/actions/azure-login):

   1. When complete, the `az ad sp create-for-rbac` command displays JSON output in the following form (which is specified by the `--sdk-auth argument`):

      ```json
      {
        "clientId": "<GUID>",
        "clientSecret": "<GUID>",
        "subscriptionId": "<GUID>",
        "tenantId": "<GUID>",
        (...)
      }
      ```

   1. In your repository, use **Add secret** to create a new secret named `AZURE_CREDENTIALS`.

   1. Paste the entire JSON object produced by the `az ad sp create-for-rbac` command as the secret value and save the secret.

**Comment by gcharters** [comment]
I think I have now done this.  Let me know if it's not right.  Thanks.

**Comment by git4rk** [comment]
@edburns @zhengchang907 Following secrets have been added: https://github.com/WASdev/azure.websphere-traditional.image/settings/secrets/actions
![image](https://user-images.githubusercontent.com/24283162/118070908-c5bce000-b374-11eb-83d0-48a436ed8888.png)

**Comment by edburns** [comment]
This can be closed, @git4rk .
