### ISSUE TITLE
`listAvailablePackages` returns `No packages were found`

### ISSUE THREAD

**Issue by majguo** [WASdev/azure.websphere-traditional.image#25]
Today when I'm testing the latest tWAS cluster testing offer using Ed's entitled IBMid, it always failed. I further triaged the issue and found that the command used to list available packages doesn't run as expected, which caused the entitlement check failed:
```
userName=<your.IBMid>
password=<your.IBMid.pwd>
${IM_INSTALL_DIRECTORY}/eclipse/tools/imutilsc saveCredential -secureStorageFile storage_file -userName "$userName" -userPassword "$password" -passportAdvantage
${IM_INSTALL_DIRECTORY}/eclipse/tools/imcl listAvailablePackages -cPA -secureStorageFile storage_file
```
Command output for listing available packages:
```
No packages were found.
```
I run the above command both in a vm deployed on Azure and my local laptop, with entitled and un-entitled IBMids, but get the same result.
Actually when I re-thought the issue, the similar phenomenon happened few times before, but then disappeared. However, the issue seems persist this time, not sure if the back-end service for listing available packages is down or there is something else wrong.

This issue needs to be triaged and resolved ASAP as it blocks successful tWAS cluster deployments.

**Comment by majguo** [comment]
Hello @git4rk Could you pls help take a look at this issue? Thanks.

**Comment by majguo** [comment]
Note: this issue not only breaks entitlement check, but also breaks tWAS installation, as no available packages returned.

**Comment by git4rk** [comment]
@majguo `imcl listAvailablePackages` worked for me now. Maybe it was a temporary (but long) outage. I will continue to follow up with Install team.

**Comment by git4rk** [comment]
- IM team confirmed that there were no planned outages last week.
- If another outage occurs
    - you can post in the IM forum: https://w3.ibm.com/w3publisher/capilano-installation-manager-etc/forum#/categories/service-repository-access-and-capilano-web-application-(cwa)
    - slack `@Stuart Frische`

**Comment by majguo** [comment]
Closing the ticket per @git4rk 's response.
