### ISSUE TITLE
Reorganize repo to accommodate base image creation for IHS

### ISSUE THREAD

**Issue by edburns** [WASdev/azure.websphere-traditional.image#27]
Restructure this repo so that it has two top level directories:
* **twas** — this is the existing content for the twas base image.
* **ihs** — this is new content for the ihs base image

**Comment by zhengchang907** [comment]
Hi @git4rk , I've refactored the code in this [PR](https://github.com/WASdev/azure.websphere-traditional.image/pull/32). Can you please review it?
