### ISSUE TITLE
Populate the ihs subdirectory with the necessary logic to create an ihs base image

### ISSUE THREAD

**Issue by edburns** [WASdev/azure.websphere-traditional.image#28]
## IHS repo location and offering id:

http://www.ibm.com/software/repositorymanager/com.ibm.websphere.IHS.v90

com.ibm.websphere.IHS.v90

## Plugin repo and offering ID

http://www.ibm.com/software/repositorymanager/com.ibm.websphere.PLG.v90

com.ibm.websphere.PLG.v90

## Documentation

https://www.ibm.com/docs/en/was/9.0.5?topic=environment-web-server-plug-ins-installation-information

**Comment by majguo** [comment]
Based on the latest response from  @git4rk in WASdev/azure.websphere-traditional.cluster#37, the following repository URL and offering IDs will be used:

- Repository URL: https://www.ibm.com/software/repositorymanager/entitled
- IHS offering ID: com.ibm.websphere.IHS.v90
- Plugin offering ID: com.ibm.websphere.PLG.v90
- WCT offering ID: com.ibm.websphere.WCT.v90
- IBM Java SDK offering ID: com.ibm.java.jdk.v8

Besides, an entitled IBMid is required to install these packages.
